(defun GRADE (num_grade)
  (cond ((and (>= num_grade 90) (<= num_grade 100)) "A+")
        ((and (>= num_grade 85) (< num_grade 90)) "A")
        ((and (>= num_grade 80) (< num_grade 85)) "A-")
        ((and (>= num_grade 77) (< num_grade 80)) "B+")
        ((and (>= num_grade 73) (< num_grade 77)) "B")
        ((and (>= num_grade 70) (< num_grade 73)) "B-")
        ((and (>= num_grade 67) (< num_grade 70)) "F")
        ((and (>= num_grade 63) (< num_grade 67)) "F")
        ((and (>= num_grade 60) (< num_grade 63)) "F")
        ((and (>= num_grade 57) (< num_grade 60)) "F")
        ((and (>= num_grade 53) (< num_grade 57)) "F")
        ((and (>= num_grade 50) (< num_grade 53)) "F")
        ((and (>= num_grade 0) (< num_grade 50)) "F")
        (t "Invalid Grade")
        )

)
